### ISSUE TITLE
Extreme Reactor not working after upgrade to 2.0.0

### ISSUE THREAD

**Issue by rsandell** [FTBTeam/FTB-Presents-Direwolf20-1.12#4]
* **Modpack Version**: 2.0.0

* **Issue**: After upgrading to 2.0.0 my 9x9x7 Extreme Reactor, chilled with cryotheum, isn't working.
It was full of fuel (uranium) before and after the upgrade. I first noticed that the opencomputers control program wasn't charging (same as DW uses in his single player). But manually stating it also doesn't work, the Reactor Control says "Status: Online" but it's not generating any RF.
I've tried removing a block and reforming the reactor, and also removing the computer cable, but still the same issue.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Well it's permanent, haven't tried doing another upgrade, haven't tried building a new reactor from scratch yet.

* **Mod/s Affected**: Extreme Reactors

* **Known Fix**: N/A

**Comment by rsandell** [comment]
Building a reactor from scratch works, it seems to be the upgrade that caused it to fail.
Will try next to build one in the same place as the old one.

**Comment by SnowShock35** [comment]
@rsandell The reason for this happening is most likely due to the fact that I increased the max turbine size and somehow that has an effect on reactor multi-blocks. I'm not entirely sure but if I figure out why I'll let you know. 

Otherwise as it stands this is solvable by replacing some elements of the reactor and since this update was recommended as a world restart update I will close this and say that it's a migration from 1.X.X > 2.X.X issue.
