### ISSUE TITLE
Major Bug

### ISSUE THREAD

**Issue by AshenPheonix** [FTBTeam/FTB-Presents-Direwolf20-1.12#40]
* **Modpack Version**: Both 2.1.0 and 2.2.0

* **Issue**: changing windows causes internal server on single player games to disconnect from client... which is itself. Also, Ender Pearls can be pulverized to dust, and then again into powder. Powder causes a recipe conflict between portal gun and ender io, one wants a full grid to return to dust, the other to return to an ender pearl.

* **Link to Log or Crash File Paste**: Most Recent https://paste.feed-the-beast.com/view/5cacd10c

* **Is it Repeatable?**: Many, many times

* **Mod/s Affected**: all of them

* **Known Fix**: nope

**Comment by SnowShock35** [comment]
Hello @AshenPheonix,

In future please do not combine issues. This is a bad practice to use and will make solving issues more difficult, to begin with. 

Since this is a combination of issues it will be marked as invalid and closed immediately. However, on this one occasion, I will inform you that your issues should be fixed as of 2.3.0.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈
