### ISSUE TITLE
Can't connect to server, internal exception error.

### ISSUE THREAD

**Issue by JordanAuthxr** [FTBTeam/FTB-Presents-Direwolf20-1.12#41]
* **Modpack Version**: 2.1.0

* **Issue**: When joining a server on this modpack it gives me an internal exception error, or just "Disconnected" but mainly an internal exception. This is very frustrating as I'm trying to join a small server with friends but I just can't. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/65c5c029

* **Is it Repeatable?**: Its happened every single time I've tried to connect. I have tried with different launchers with no success.

* **Mod/s Affected**: In my view, at the time of the crash it usually says 
"[18:35:15] [Netty Client IO #7/INFO] [Astral Sorcery]: [AstralSorcery] Cleaning client cache...
[18:35:15] [Netty Client IO #7/INFO] [Astral Sorcery]: [AstralSorcery] Cleared cached client data! Disconnected from server."
Not sure if this is the issue.

* **Known Fix**: N/A

Note: Please consider the issue even when I have optifine, I have tried it without the mod many times and I installed it to see if it would help, as much as I would like to run without it to give you the issue without any modifications, I really don't want to wait another long period for the modpack to load just for the same outcome.

**Comment by TheMajesticPickle** [comment]
Im having similar issues. What Ive tried is disabling all app behavior-based and website virus protection and usually you can get in a server eventually, but there is surely an issue within the pack itself because it is still difficult for people to join.

The closest thing Ive seen to this issue and its solution was an issue within forestry. Try disabling forestry and its dependents within the server and all the users and see if it works. I havent tried it myself, because a few of the people on my server are not bright enough to disable/add/remove a mod from the pack, lol

**Comment by TwoPointInfinity** [comment]
If i could upvote this i would. This needs to be addressed. I get disconnected while joining servers as well sometimes and i also get kicked as well. i have my own server where this is a constant issue and i am willing to provide any information needed to getting this fixed as its the main issue i have.

**Comment by JordanAuthxr** [comment]
Yea I just gave up, couldn't fix it.

**Comment by SnowShock35** [comment]
Hello Everyone,

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

Apologies for the lateness of the reply. I was unaware for quite some time what was causing this issue as well as the impact this issue was having on users. I greatly appreciate your patience on the matter and to my knowledge, this should be fixed as of 2.3.0 which will be released publically very soon.

As such this issue will now be marked for closure until the update is released and will be closed shortly following its release.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)

**Comment by SpiritWolfie** [comment]
> 
> 
> Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)

As far as myself and my group can see this has not been resolved as of the latest direwolf 20 mod pack

We are consistently getting this almost everytime we try to log in.

**Comment by SnowShock35** [comment]
@SpiritWolfie I have another version coming out in a day or two, keep me posted after that update if the issue still occurs. Thanks

**Comment by SpiritWolfie** [comment]
> @SpiritWolfie I have another version coming out in a day or two, keep me posted after that update if the issue still occurs. Thanks

Hi there snowshock!

Do you mean a actual update to the direwolf 20 pack? (like the whole thing) or a independent mod that is in the direwolf pack and if you mean that which one so we know which one to update.

Cause I know allot of the mods on the direwolf 20 pack are really out dated and some of the stuff is insanely buggy I.E mining dimension suffocating people in the wall, Just roaming around twilight forest causing server crashes etc.

Also can you please provide a direct link or whatever when you release the update so I know precisely which one to look at?

**Comment by SnowShock35** [comment]
Hey @SpiritWolfie.

It was an update to the entire pack. If you didn't see the tweet about it here's a link to the release notes for that update. https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2690085

To install the update you will have to go through the Twitch Desktop App directly.
