### ISSUE TITLE
i found a doop bug

### ISSUE THREAD

**Issue by hk112** [FTBTeam/FTB-Presents-Direwolf20-1.12#43]
i had the moveing wand from not enough wands in my hand i was faceing a multi-block from immersive engineering and hold right click with and it dooped the block that was there before the multiblock was formed

**Comment by hk112** [comment]
i am on the dirediscord as well if want to see it in action i do i share screen call thing so you can see it

**Comment by SnowShock35** [comment]
You have failed to comply with the issue template set out on this repository. As a result of your actions, this issue will now be closed and locked indefinitely. 

Failure to comply with or challenging this rule repeatedly will result in all further issues you post being ignored.

The issue template is designed to make reporting issues easier for users and fixing issues easier for us. By failing to do so you waste both your own and developers time as this creates more issues to sift through and manage.

Please see to it that you create a new issue following the template so that we can address this issue properly. 

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈
