### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Daboudreaux** [FTBTeam/FTB-Presents-Direwolf20-1.12#45]
* **Modpack Version**: 2.2.0
* **Issue**: I played at first without much issue.  Then yesterday I started getting lag spikes so bad that the game would freeze up every minute.   I'm not sure if it's related but now I have some options in the top left corner that appear to be for multiplayer, but I'm not playing multiplayer.  I'm just doing Singleplayer.

* **Link to Log or Crash File Paste**: 
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/files/2268555/latest.log)

* **Is it Repeatable?**: It happens now every time I play.
* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by Daboudreaux** [comment]
I solved the problem by going back to the default resource pack, but now I have no sounds.

**Comment by SnowShock35** [comment]
Hello @Daboudreaux 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

I'm glad to hear that you figured it out. As a word of warning always restart your game if you change your resource pack as it eats memory up where it has to reload every single texture, sound and model. It happens to cause some weirdness with some mods too. Whether or not that is related to sound I'm not entirely certain. I imagine that your lag spikes were likely caused by running out of allocated RAM as texture packs can often require additional ram to run due to the higher quality of the textures. 

If you have any further problems be sure to open a new issue and I will take a look at it for you.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈
