### ISSUE TITLE
Direwolf20 - Reborn Storage 3.2 ignores crafting CPUs

### ISSUE THREAD

**Issue by BlueLueBoy** [FTBTeam/FTB-Presents-Direwolf20-1.12#52]
* **Modpack Version**: 2.2.0

* **Issue**: The reborn storage multiblock seems to ignore crafting CPUs for crafting operation speed. It does accept them as valid blocks and the refined storage controller lists them draining 1 FE/t for each of them but no matter how many I put in the multiblock, the crafting speed remains the same: very slow, whether there are none, one or several dozens…

* **Link to Log or Crash File Paste**: Technically nothing crashes so there is no crash report and no errors get thrown to the console when I auto-craft stuff. It’s just very slow…

* **Is it Repeatable?**: Yes, I’ve tried on a new test world and can observe the same behavior so it has nothing to do with my world.

* **Mod/s Affected**: Probably _Reborn Storage 3.2.0.6_ but it could also be _Reborn Core_, _Refined Storage_ or _Refined Storage Addons_

* **Known Fix**: Reversing back to DW20 v2.1.0, works, but that's hardly a fix, isn't it?

**Comment by BlueLueBoy** [comment]
'K, I have found an easy and quite classical workaround: I updated all four refined/reborn storage mods to latest versions and it's now working as it should...

**Comment by SnowShock35** [comment]
Thank you for reporting this issue. The next update will include updates to these mods natively in the mod pack. For the time being yes your workaround will work just be cautious as no further support will be offered if you have a modified version of the pack.

**Comment by Kanzuke117** [comment]
> will be fixed as of version `version`

nice

@SnowShock35 is there a reason you've suddenly gone obnoxiously corporate in all your replies? Reading 15 emails today with the same copy-pasted response got quite tiring...

**Comment by SnowShock35** [comment]
@Kanzuke117 Hey,

First of all, thank you for bringing this up. I wanted to mention why my replies are so "copy-pasted" looking and as well as being formal and very "corporate-like".

To begin with, the copy-paste like replies is simply utilising the saved-replies feature GitHub now offers. It means I can consistent and fair to everyone in what I say as well as being able to get through bug reports quicker. Don't worry I'm not some obnoxious robot just yet. 

My real life recently has been incredibly busy from finishing my college education extremely late due to being behind on work, family issues and working and preparing for university I have had a hard time keeping up with updates and issue tracking - which is quite obvious from the recently lacking amount of updates. 

In 12 days I move into University at which point my life is going to likely become even busier, but I'm not willing to stop doing what I love because of it though. This is one of my only enjoyable passions during my free time and so I want to keep going with it. However, to be able to do that I've got to be able to keep on top of things and having the replies means I can sift through issues really quickly, get them fixed and then get updates out. 

I'm not rushing anything either I still put the same amount of effort into every pack update I usually would. I'm quite a thorough individual. 

As for my more formal response I'm just trying to be professional and consistent with what I say - after all, I'm working on behalf of a company as a volunteer. I am open to taking suggestions to make my replies a bit less formal/corporate sounding because like I said I'm not a robot and I do have a life and feelings too. 

Apologies for not specifying the version. It's 2.3.0.

Hope this answers your question, let me know if there's anything further you wish to discuss. 

- SnowShock35 ☃️ 🙂

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)
