### ISSUE TITLE
Blood Magic structure renders are only visible from certain angles...?

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Presents-Direwolf20-1.12#70]
* **Modpack Version**: 2.3.0 

* **Issue**:  That's basically it in the title. The instruction book says to shift click the (other) book on the altar to get the structure render to appear in the first place and since it's only visible from certain angles, it's often hard to tell if the render has even been "turned on" or not. I have made an imgur album [here](https://imgur.com/a/0E4hIaX) of three pairs of demonstrative before and after pictures.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yeah, sure.

* **Mod/s Affected**: well, blood magic probably. I could see it being some other mod messing with rendering, or even my video card I guess. At that point it's outside of my ability to diagnose though.

* **Known Fix**:

**Comment by SnowShock35** [comment]
So the Inspectoris Scandalum only shows the imaginary structures when the blood altar is visible on your screen. This is likely by design to avoid large amounts of lag. 

I can potentially make a request to the blood magic authors to somehow increase this range however, there is no certainty that the issue will be addressed.
