### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Direwolf20-1.12#78]
Let's go ahead and push another round up updates for DW20.

Many fixes have been made and many mods are on new release builds.

**Comment by Shybella** [comment]
@SnowShock35 

Been asking since Oct.. Don't be a rude person. Just show some acknowledgement. It really makes you look bad too when you come to only close my issue but not help anyone else. Pretty sure asking a question every 6 months isn't spam but exactly the opposite of spam.

**Comment by SnowShock35** [comment]
Hi @Shybella,

Apologies for the lack of updates over the past few months. Since September I've been going through my first year of university as well as a whole load of other personal things. 

I am currently working on an update and it should drop before Monday. 

Thank you for your patients.
- Snow.
