### ISSUE TITLE
Iron gear recipe is broken in pack 2.4.0

### ISSUE THREAD

**Issue by Laventry** [FTBTeam/FTB-Presents-Direwolf20-1.12#84]
The current crafting table recipe is overruled by an advanced generator recipe. Leaving the only way to craft your first iron gear with a tinkers setup.

**Comment by Krater107a** [comment]
Can confirm this problem as well in pack 2.4.0. Oddly enough, when I tried to crafttweaker a new recipe for the iron gear; no matter what the recipe will give 64 diamond instead. Very strange.

**Comment by trav90** [comment]
I too can confirm this problem in version 2.4.0 of the mod pack

**Comment by Sebastiaan-75** [comment]
I also have the same issue.

**Comment by flungloaf** [comment]
+1

**Comment by plaguewolf** [comment]
Got pretty annoyed by this bug, so i made a crafttweaker fix that adjusts the "iron frame" recipe from advanced generators. Basically i just rearranged the iron ingots into the corners instead of the sides of the crafting space, which would honestly make more sense in the first place.

{Your Modpack Dir}/scripts/00_default.zs
/* Fixing derped iron gear recipe */
recipes.remove(<advgenerators:iron_frame>);
recipes.addShaped(<advgenerators:iron_frame> * 2, [
  [<ore:ingotIron>, null, <ore:ingotIron>],
  [null, null, null],
  [<ore:ingotIron>, null, <ore:ingotIron>]
]);

**Comment by CodeCorrupt** [comment]
@plaguewolf I tried your quick fix (applied to both server and client `scrips/00_default.zs`) to no avail. Are there any additional steps besides appending that snippet?

_Using Direwolf20 1.12 v2.4.0_


**Edit**
Found the fix on my own. `<>` are needed around the tags. Below is what worked for me:
```
/* Fixing derped iron gear recipe */
recipes.remove(<advgenerators:iron_frame>);
recipes.addShaped(<advgenerators:iron_frame> * 2, [
[<ore:ingotIron>, null, <ore:ingotIron>],
[null, null, null],
[<ore:ingotIron>, null, <ore:ingotIron>]
]);
```

**Comment by Sebastiaan-75** [comment]
Well, a workaround is to build a Thermal Expansion Compactor, upgrade it to hardened and place an Gearworking Die in the Augment slot, this allows you to create iron gears as well.

**Comment by scotpgot** [comment]
Still an issue two months later... :(

**Comment by SnowShock35** [comment]
Thank you, everyone, for your patients. 

I have fixed the issue and it will be available in the next update which will be released within the next day or so.
